# Generated by Django 2.2.10 on 2021-07-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
