# Generated by Django 2.2.10 on 2021-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='active', max_length=200),
            preserve_default=False,
        ),
    ]
