# Generated by Django 2.2.10 on 2021-07-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='frequency',
            field=models.CharField(default='daily', max_length=200),
            preserve_default=False,
        ),
    ]
