# Generated by Django 2.2.10 on 2021-07-24 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_question_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 1, 1)),
            preserve_default=False,
        ),
    ]
