# Generated by Django 2.2.10 on 2021-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210724_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='start_date',
            field=models.DateField(),
        ),
    ]
