# Generated by Django 2.2.10 on 2021-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiveData', '0002_auto_20210701_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='response_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
