# Generated by Django 2.2.10 on 2021-07-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiveData', '0003_userresponse_response_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
    ]
