# Generated by Django 2.2.10 on 2021-07-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiveData', '0005_auto_20210702_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='response',
            new_name='response_feeling',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='response_type',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response_summary',
            field=models.CharField(default='this is the summary', max_length=200),
            preserve_default=False,
        ),
    ]
