# Generated by Django 2.2.10 on 2021-07-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiveData', '0006_auto_20210703_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_feeling',
            field=models.IntegerField(),
        ),
    ]
