# Generated by Django 2.2.10 on 2021-07-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiveData', '0007_auto_20210703_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response_summary',
            field=models.CharField(max_length=1000),
        ),
    ]
